### PR TITLE
new:usr: Added project proposal for S17-IR-P012

### PR DESCRIPTION
**Pull request by ssheybani**
Updated S17-IR-P012 directory with project proposal files.

### CODE REVIEW

**Comment by laszewsk** [comment]
reject: you have not addressed the amin issues

a) README is not complete.

I am merging anyways, but your report will not be seen as submission is incomplete

**Comment by laszewsk** [comment]
ValueError: PATTERN github NOT SET IN README. CURRENT: YOUR GITHUB USERNAME

**Comment by laszewsk** [comment]
PLEASE FIX YOUR README.rst FILES!
See the details error message in your pull request
ValueError: PATTERN hid NOT SET IN README. CURRENT: ENTER YOUR HID HERE.
Seems you are the only student that has this issue. This will have the effect taht we will programatically reject all future pull requests if you have not fixed them.

**Comment by ssheybani** [comment]
I'm sorry, but I'm confused about which part of my README file is incorrect. I have tried to follow the same pattern that other students have used, and all of them have resulted in an error. I also talked to one of the TAs today about it and he couldn't also tell what was wrong. So he suggested me to contact Mr. Badi.

**Comment by laszewsk** [comment]
readme in top dir.

**Comment by laszewsk** [comment]
please get in contact with TAs if unclear

**Comment by laszewsk** [comment]
you can naturally also compare with what other students have done, as all papers and projects and hid dirs are public

**Pull request merged**
