### PR TITLE
revised paper1; attempt #1

### PR DESCRIPTION
**Pull request by eunosm3**
I made changes for nearly all of the comments.  I marked those items as "Corrected01"  

I added "RESPONSE: <foo>" to a small number of comments b/c I would like further feedback.

I did not update two of the items due to external factors.  Those items remain "pending".

### CODE REVIEW

**Comment by laszewsk** [comment]
Please do not mix project and paper pull requests they must stay separate. As you change in paper1 teh wrong file, we can not accept this pull request which as the impact that we can not accept your report either. I strongly recommned to keep pull requests logically separate. Thus if you do something wrong in one the other still can get accepted.

Also paper1/report.tex maust be used to do your cahanges and not paper1/report-review.tex which must stay uncahnged so TAs can compare what you have improved

**Comment by laszewsk** [comment]
reject: due to above reasons

**Comment by eunosm3** [comment]
My apologies for editing paper1/report-review.tex.  I did, indeed, begin editing it for my revised submission.  I should have started off editing in paper1/report.tex.  

For the sake of clarity, I did make my changes in paper1/report.tex after saving a copy of paper1/report-review.tex as paper1/report.tex, i.e., saving over the paper1/report.tex that did not have any comments.  Will paper1/report.tex pass muster if my comments, my own "\TODO" lines, remain in the paper?  Or should I eliminate those, too?   That is, should the submission be a "clean copy"?  

I ask because I included my own comments in my revision in order to a) mark the changes I made as completed and b) to ask for further clarification on a couple of items.  If you look at my paper1/report.tex, you will see the instructor feedback from the original submission, as well as my responses to the instructor feedback.

Finally, regarding your comment about mixing report and project submissions, I do not understand the critique.  When I look at the pull request (PR #155), it has three document changes: paper1/report.tex, paper1/report.pdf and paper1/report-review.tex.  I made my project submission sometime Saturday, which was merged well before I made the paper1 submission.  What am I missing here?

**Comment by laszewsk** [comment]
comment about separate pull requests I will not accept any pull requests that modify report-review.tex

**Comment by laszewsk** [comment]
I am closing this pul request as it includes a modification to report-review.tex

**Pull request closed without merging**
