### PR TITLE
fix:dev: S17-IR-2012 paper1 review

### PR DESCRIPTION
**Pull request by vibhatha**
Review added and new files were committed.

### CODE REVIEW

**Comment by vibhatha** [comment]
I didn't change anything in those files.

With Regards,
Vibhatha Abeykoon

**Comment by vibhatha** [comment]
Dimitar please give me instructions on this, can you help me to fix it and
learn it.

With Regards,
Vibhatha Abeykoon

**Comment by laszewsk** [comment]
do you guys want to realy be that specific, why not just stick to report.tex and make comments there, students shuld by now know how to do references … so just mention ref # is wrong should be finr in the report.tex.

**Comment by vibhatha** [comment]
okay professor. I can understand.

With Regards,
Vibhatha Abeykoon

**Comment by dimitargnikolov** [comment]
Sounds good to me. I will send a message to the list, so everyone sees it.

**Comment by dimitargnikolov** [comment]
@vibhatha Based on the discussion on the mailing list and the process outline by Gregor, let's not include references-review.tex or commit a new version of report.pdf. You need to revert report.pdf to the previous version with 'git checkout', remove references-review.bib, and make sure report-review.tex uses references.bib.

**Comment by vibhatha** [comment]
Yes I may have added those files, but actually report-review.tex refers the
references.bib. I will do the modifications. Thanks Dimitar.

With Regards,
Vibhatha Abeykoon

**Comment by vibhatha** [comment]
I deleted the reference-review.bib file. Can anyone check my pull request
and if it is okay please tell me.

With Regards,
Vibhatha Abeykoon

**Comment by dimitargnikolov** [comment]
I would also revert paper1/S17-IR-2012/report.pdf to the previous version committed by the student. That way we're not modifying any part of their submission.

$ git checkout paper1/S17-IR-2012/report.pdf
$ git commit -m "..." paper1/S17-IR-2012/report.pdf
$ git push

**Comment by vibhatha** [comment]
Yes, I know, but I didn't modify the report.tex for any reason. But the
make process might have created the new file. I don't think it won't do any
changes for the pdf file as there are no changes done to the original
report.tex file. And thanks Dimitar for following up.

With Regards,
Vibhatha Abeykoon

**Comment by vibhatha** [comment]
I know. I will avoid this.

With Regards,
Vibhatha Abeykoon

**Pull request merged**
