### PR TITLE
chg:usr Add PDF report as requested by TA

### PR DESCRIPTION
**Pull request by karvenka**

### CODE REVIEW

**Comment by karvenka** [comment]
Hello Professor
   The PDF in P009 is not getting generated automatically.I am able to compile the report in my local.Seems the script is expecting an existing PDF when it recompiles.So checking in the PDF .Can you please approve this.

**Comment by karvenka** [comment]
Hi professor 
The proceedings is correctly updated with our latest report.It is just the pdf is not being created in the project directory if it is not there.

**Comment by laszewsk** [comment]
I think i fixed it, please check

**Comment by laszewsk** [comment]
also look at previous pull request still in queue, make sure they are included

**Pull request merged**
